# Reference image
FROM docker.elastic.co/kibana/kibana:8.19.17@sha256:a0ab425c2ae1688c09fbe1956b0d55009960cbc55564b26a55c946a589f0276c

# Metadata
LABEL maintainer="Daniel Wydler"
LABEL org.opencontainers.image.authors="Daniel Wydler"
LABEL org.opencontainers.image.description="A Python package and CLI for parsing aggregate and forensic DMARC reports."
LABEL org.opencontainers.image.documentation="https://github.com/wydler/parsedmarc-docker/blob/master/README.md"
LABEL org.opencontainers.image.source="https://github.com/wydler/parsedmarc-docker"
LABEL org.opencontainers.image.title="wydler/parsedmarc-kibana"
LABEL org.opencontainers.image.url="https://github.com/wydler/parsedmarc-docker"


