# Reference image
FROM wydler/logrotate:1.2.6@sha256:88d137c361436ce6a006f3d08f135c461bcdf392c95a26c1b4cd84adfd5f9bd7

# Metadata
LABEL maintainer="Daniel Wydler"
LABEL org.opencontainers.image.authors="Daniel Wydler"
LABEL org.opencontainers.image.description="A Python package and CLI for parsing aggregate and forensic DMARC reports."
LABEL org.opencontainers.image.documentation="https://github.com/wydler/parsedmarc-docker/blob/master/README.md"
LABEL org.opencontainers.image.source="https://github.com/wydler/parsedmarc-docker"
LABEL org.opencontainers.image.title="wydler/parsedmarc-logrotate"
LABEL org.opencontainers.image.url="https://github.com/wydler/parsedmarc-docker"
